import { LARGE_FONT, MEDIUM_FONT, SMALL_FONT } from '../utils/constants';

function getFontSizeFromID(id) {
    const el = document.getElementById(id);
    const fontSize = parseInt(window.getComputedStyle(el).fontSize);
    return fontSize;
}

function getScrollbarWidth() {
    // This function was generated by ChatGPT-3
    // Create a dummy element with a scrollbar
    const scrollDiv = document.createElement('div');
    scrollDiv.style.width = '100px';
    scrollDiv.style.height = '100px';
    scrollDiv.style.overflow = 'scroll';

    // Append the dummy element to the document
    document.body.appendChild(scrollDiv);

    // Calculate the scrollbar width
    const scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth;

    // Remove the dummy element from the document
    document.body.removeChild(scrollDiv);

    return scrollbarWidth;
}

/**
 * Determines what percentage of the slider a thumb or mark should be offset
 * from the left based on its value. 
 * @param {*} value the font size indicated by the mark or thumb. 
 * @returns 0% for SMALL_FONT, 50% for MEDIUM_FONT, 100% for LARGE_FONT.
 */
function getLeft(value) {
    switch (value) {
        case SMALL_FONT:
            return '0%';
        case MEDIUM_FONT:
            return '50%';
        case LARGE_FONT:
            return '100%';
        default:
            throw new Error(`${value} passed to getLeft should be one of [${SMALL_FONT}, ${MEDIUM_FONT}, ${LARGE_FONT}]`);
    }
}

export { getFontSizeFromID, getLeft, getScrollbarWidth };
